# docker-compose.yaml
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:${JENKINS_TAG}
    privileged: true
    user: root
    ports:
     - 8080:8080
     - 50000:50000
    container_name: jenkins
    volumes:
      - ../jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  agent:
    image: "aurora/${AGENT_NAME}:${AGENT_TAG}"
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8AlUe4qgjAHrivgQaHCAxTWjJG77KQr6CXfYJbG82gnGM70b2IqtgeDiBCiR6mTaqN/0Uqzdb8FSVeMhB2DX7jUjRpNiSmEQl8B0zMnHXOkRKP404zOuCgH+HsGs8Ic79Uwcm0vwlBD6cRYBd7PYbY6zSxj1PME+sGHFaXC/nHLe4mnhv5NFrFcEy0d6nTPXTNLXfk13ggKMsywGC0+xa/tvuOAJZ/vIKJfBL5ZN9hm9YPtEdheXIz57vdScRyiV8+qTZTGkQzl4VDIrQMzfsm6lYx/FY/a8vr57tXDGjn0nB8HnRzRAYiFjuO4/Ohc1hhgpcr6KDQdiRVCZSbuttLJKQRLgx+nVeUdRIhnV8ywQZrSBD6w9IfIvS7MC2y/Cp7TRlyjBydTozCND2zqFwaJInxqJ259KZpNgvpUf5HsoKFMouwGgGY1+E5DqlrjRxUHcNSmFQZw2+HQatyqxItX3j2Hm2qGsA3rbR2OHqsvwnYSZO+ntHGPhTXZqjYDM= brottenberg@MCBROTTEN-32XZM
